<a href="https://colab.research.google.com/github/namanmanchanda09/pytorch-basics/blob/main/Pytorch_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch 
import numpy as np

In [ ]:
print(torch.__version__)

1.7.0+cu101


# Tensors from Numpy Arrays

In [ ]:
# declaring numpy array
arr = np.array([1,2,3,4,5,])
print(arr)
print(arr.dtype)
type(arr)

[1 2 3 4 5]
int64


numpy.ndarray

In [ ]:
# numpy array to tensor
x = torch.from_numpy(arr)
print(x.dtype)
print(x)
type(x)

torch.int64
tensor([1, 2, 3, 4, 5])


torch.Tensor

In [ ]:
# general way to convert into tensor
torch.as_tensor(arr)

tensor([1, 2, 3, 4, 5])

In [ ]:
arr2d = np.arange(0.0,12.0)
arr2d = arr2d.reshape(4,3)
x2 = torch.from_numpy(arr2d)
x2

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)

In [ ]:
# from_numpy creates a direct link between numpy array and tensor
arr = np.array([1,2,3,4,5])
x = torch.from_numpy(arr)
print(x)
arr[0] = 99
print(x)

tensor([1, 2, 3, 4, 5])
tensor([99,  2,  3,  4,  5])


In [ ]:
# torch.Tensor or torch.FloatTensor creates a tensor of type float & torch.tensor infers the datatype from original object
arr = np.array([1,2,3,4,5])
x = torch.tensor(arr)
y = torch.Tensor(arr)
print(x.dtype)
print(y.dtype)
print(x)
print(y)

torch.int64
torch.float32
tensor([1, 2, 3, 4, 5])
tensor([1., 2., 3., 4., 5.])


In [ ]:
# Creating a tensor as a copy of numpy array
my_arr = np.arange(0,10)
print("Numpy array :" ,my_arr)
my_tensor = torch.tensor(my_arr)
print("Tensor :", my_tensor)
my_arr[0] = 99
print("Modified numpy array :", my_arr)
print("Tensor :", my_tensor) 

Numpy array : [0 1 2 3 4 5 6 7 8 9]
Tensor : tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Modified numpy array : [99  1  2  3  4  5  6  7  8  9]
Tensor : tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


# Tensors from scratch

In [ ]:
# allocated space in memory for a tensor
torch.empty(4,2)

tensor([[8.4087e-36, 0.0000e+00],
        [3.3631e-44, 0.0000e+00],
        [       nan, 0.0000e+00],
        [1.1578e+27, 1.1362e+30]])

In [ ]:
# tensor of zeros
torch.zeros(4,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
# tensor of ones
torch.ones(3,4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
# same function as numpy
torch.arange(0,18,2).reshape(3,3)

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])

In [ ]:
# same function as numpy
torch.linspace(0,18,12).reshape(4,3)

tensor([[ 0.0000,  1.6364,  3.2727],
        [ 4.9091,  6.5455,  8.1818],
        [ 9.8182, 11.4545, 13.0909],
        [14.7273, 16.3636, 18.0000]])

In [ ]:
# python list to tensor
my_tensor = torch.tensor([1,2,3])
print(my_tensor)
my_tensor.dtype

tensor([1, 2, 3])


torch.int64

In [ ]:
my_tensor = my_tensor.type(torch.int32)
print(my_tensor)
my_tensor.dtype

tensor([1, 2, 3], dtype=torch.int32)


torch.int32

In [ ]:
# random number from uniform distribution
torch.rand(4,3)

tensor([[0.9818, 0.7321, 0.4635],
        [0.0771, 0.5712, 0.4034],
        [0.5615, 0.5102, 0.7191],
        [0.4294, 0.9525, 0.2274]])

In [ ]:
# random number from standard normal uniform distribution - mean 0 and standard deviation 1
torch.randn(4,3)

tensor([[-1.3185,  0.0861,  0.8723],
        [-0.6660,  1.4159, -0.4158],
        [ 0.8827, -0.1727,  1.4072],
        [-0.8261, -1.8555, -0.5035]])

In [ ]:
torch.randint(low=0,high=10,size=(5,5))

tensor([[7, 8, 1, 9, 4],
        [8, 9, 4, 2, 1],
        [2, 1, 0, 6, 3],
        [7, 4, 7, 0, 7],
        [8, 8, 6, 9, 1]])

In [ ]:
# random tensor with the same shape as incoming tensor
x = torch.zeros(2,5)
print(x.shape)
torch.rand_like(x)

torch.Size([2, 5])


tensor([[0.7168, 0.2406, 0.4293, 0.1874, 0.1402],
        [0.9634, 0.8160, 0.5423, 0.1882, 0.5113]])

In [ ]:
torch.randn_like(x)

tensor([[-0.0278,  0.0033, -0.8479, -0.6437,  0.7324],
        [ 0.5822, -0.1114, -2.3446,  0.0071, -0.2544]])

In [ ]:
torch.randint_like(x,low=0,high=11)

tensor([[ 0.,  0.,  4., 10., 10.],
        [ 7.,  3.,  3.,  9.,  6.]])

In [ ]:
# setting seed valye
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

# Tensor Operations

In [ ]:
x = torch.arange(6).reshape(3,2)
x

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [ ]:
# indexing a tensor
print(x[1,1])
type(x[1,1])

tensor(3)


torch.Tensor

In [ ]:
print(x[:, 1])
print(x[:, 1:])

tensor([1, 3, 5])
tensor([[1],
        [3],
        [5]])


In [ ]:
x = torch.arange(10)
print(x)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [ ]:
# reshape and view
print(x.view(2,5))
print(x)
print(x.reshape(2,5))
print(x)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [ ]:
x = torch.arange(10)
print(x.shape)

torch.Size([10])


In [ ]:
# letting PyTorch infer the shape
z = x.view(2,-1)
print(z)
z = x.view(-1,5)
print(z)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


# Tensor arithmetic

In [ ]:
a = torch.tensor([1.,2.,3.])
b = torch.tensor([4.,5.,6.])
print(a)
print(b)
print(a.dtype)
print(b.dtype)

tensor([1., 2., 3.])
tensor([4., 5., 6.])
torch.float32
torch.float32


In [ ]:
print(a+b)
print(torch.add(a,b))

tensor([5., 7., 9.])
tensor([5., 7., 9.])


In [ ]:
# changing tensor in place - use (add_)
a.add(b)
print(a)
print(a.add_(b))
print(a)

tensor([1., 2., 3.])
tensor([5., 7., 9.])
tensor([5., 7., 9.])


In [ ]:
a = torch.arange(start = 1, end = 4, dtype=torch.float32)
b = torch.arange(start = 4, end = 7, dtype=torch.float32)
print(a)
print(b)

tensor([1., 2., 3.])
tensor([4., 5., 6.])


In [ ]:
# dot product of 2 tensors
a.dot(b)

tensor(32.)

In [ ]:
# cross product 
a = torch.tensor([[0,2,4],[1,3,5]])
b = torch.tensor([[6,7],[8,9],[10,11]])
print(a)
print(b)
print(a.shape)
print(b.shape)

tensor([[0, 2, 4],
        [1, 3, 5]])
tensor([[ 6,  7],
        [ 8,  9],
        [10, 11]])
torch.Size([2, 3])
torch.Size([3, 2])


In [ ]:
torch.mm(a,b)

tensor([[56, 62],
        [80, 89]])

In [ ]:
a @ b

tensor([[56, 62],
        [80, 89]])

In [ ]:
# euclidean norm
x = torch.arange(1,4, dtype=torch.float32)
print(x)
print(x.norm())

tensor([1., 2., 3.])
tensor(3.7417)


In [ ]:
# return the number of elements
print(x.numel())

3
